version: "3.9"

services:
  # Mock service - stable image from Docker Hub
  mock-service:
    image: ozkansisik/mock-pokemon-api:latest
    networks:
      - test-network

  # API tests - built with build number
  api-tests:
    image: ozkansisik/pokemon-api-tests:${BUILD_NUMBER:-latest}
    depends_on:
      - mock-service
    environment:
      - BASE_URL=http://mock-service:3001/api
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    networks:
      - test-network


# Define a custom network for service communication
networks:
  test-network:
    driver: bridge
