name: CI - Mock Pokemon API Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Show Docker Compose version
        run: docker-compose --version

      - name: List running containers
        run: docker compose ps

      - name: Show BASE_URL environment variable
        run: echo "BASE_URL=$BASE_URL"

      - name: Run services with Docker Compose
        run: docker-compose up --build -d

      - name: Wait for services to be ready
        run: sleep 10

      - name: Run tests
        run: docker-compose run --rm api-tests

      - name: Stop and remove containers
        run: docker-compose down

