name: CI - Mock Pokemon API Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: docker build -t mock-pokemon-api .

    - name: Run Docker Container
      run: |
        docker run -d --name mock-pokemon-api -p 3001:3001 mock-pokemon-api
        echo "Waiting for API to be ready..."
        for i in {1..10}; do
          curl -s http://localhost:3001/api/pokemons && break
          echo "Still waiting..."
          sleep 2
        done

    - name: Check running containers
      run: docker ps


    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: pytest tests/

    - name: Show Docker Logs (if tests fail)
      if: failure()
      run: docker logs mock-pokemon-api

    - name: Cleanup Docker Container
      if: always()
      run: |
        docker stop mock-pokemon-api || true
        docker rm mock-pokemon-api || true
